image:
  repository: ghcr.io/tautulli/tautulli
  pullPolicy: IfNotPresent
  tag: v2.15.0@sha256:f13daee2a403a95a51902b2625de5f6b944f034e9cd790e9d2a0c5e84c9842cb
workload:
  main:
    podSpec:
      containers:
        main:
          command:
            - python
            - Tautulli.py
          args:
            - --config
            - /config/config.ini
            - --datadir
            - /config
service:
  main:
    ports:
      main:
        port: 8181
        targetPort: 8181
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
