annotations:
  truecharts.org/category: media
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: 4.93.1
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: Run VS Code on any machine anywhere and access it in the browser.
home: https://truecharts.org/charts/stable/code-server
icon: https://truecharts.org/img/hotlink-ok/chart-icons/code-server.webp
keywords:
- code
- vs
- visual studio
- vscode
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: code-server
sources:
- https://github.com/cdr/code-server
- https://github.com/truecharts/charts/tree/master/charts/stable/code-server
- https://hub.docker.com/r/codercom/code-server
type: application
version: 12.2.1
