{
 "title": "Database Information",
 "tags": [ "TeslamateCustomDashboards" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "length_unit",
    "query": "select unit_of_length from settings limit 1;"
   },
   {
    "name": "car_id",
    "label": "Car",
    "query": "SELECT name AS __text, id AS __value FROM cars ORDER BY display_priority ASC, name ASC;"
   }
  ]
 },
 "panels": [
  {
   "title": "Mileage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ROUND(convert_km((max(odometer) - min(odometer))::numeric, '$length_unit'),0)|| ' $length_unit' as \"Logged\"\nfrom positions where car_id = $car_id;"
    },
    {
     "rawSql": "select ROUND(convert_km(ROUND(odometer::numeric,0), '$length_unit'),0) || ' $length_unit'  as \"Odometer\"\nfrom positions \nwhere car_id = $car_id\norder by date desc \nlimit 1;"
    }
   ]
  },
  {
   "title": "Stats",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) AS \"Charges\" FROM charging_processes WHERE car_id=$car_id \n"
    },
    {
     "rawSql": "SELECT COUNT(id) AS \"Drives\" FROM drives WHERE car_id=$car_id "
    }
   ]
  },
  {
   "title": "Software",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) as \"Nº Car Updates\"\nFROM Updates \nWHERE car_id = $car_id\n"
    },
    {
     "rawSql": "select split_part(version, ' ', 1) as \"Current Car Firmware\" \r\nfrom updates \r\nwhere car_id = $car_id \r\norder by start_date desc \r\nlimit 1"
    }
   ]
  },
  {
   "title": "Incomplete Data",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) as \"Charges not closed\"\nFROM charging_processes \nWHERE car_id = $car_id AND end_date is null\n"
    },
    {
     "rawSql": "SELECT COUNT(id) AS \"Drives not closed\"\r\nFROM drives \r\nWHERE car_id = $car_id AND end_date is null"
    }
   ]
  },
  {
   "title": "About incomplete data",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": {
    "content": "You can go to the <a href='./d/jchmIDopVO_mgz/incomplete-data'  target='_blank'>\nIncomplete Data dashboard</a> <br />\nto see details of the **Drives** or **Charges** not closed.\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  start_date AS \"time\",\n  start_km\nFROM drives\nWHERE\n  $__timeFilter(start_date)\nORDER BY 1"
    }
   ]
  },
  { "title": "Database Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "type": "table",
   "gridPos": { "h": 16, "w": 5, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT \r\n   relname AS \"Table\",\r\n   pg_size_pretty(pg_total_relation_size(relid)) As \"Size\"\r\nFROM \r\n   pg_catalog.pg_statio_user_tables\r\nORDER BY \r\n   pg_total_relation_size(relid) DESC;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 16, "w": 5, "x": 5, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT table_name AS \"Table Name\", \r\n       (xpath('/row/cnt/text()', xml_count))[1]::text::int AS \"Row Count\"\r\nFROM (\r\n    SELECT table_name, \r\n           query_to_xml(format('SELECT count(*) as cnt FROM %I.%I', table_schema, table_name), false, true, '') AS xml_count\r\n    FROM information_schema.tables\r\n    WHERE table_schema NOT IN ('pg_catalog', 'information_schema')\r\n) AS t\r\nORDER BY 2 DESC;"
    }
   ]
  },
  {
   "title": "Indexes",
   "type": "table",
   "description": "These statistics can help you evaluate the efficiency of your indexes.\n\nYou should reindex all the database periodically.",
   "gridPos": { "h": 16, "w": 14, "x": 10, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    relname AS \"Table\",\r\n    indexrelname AS \"Index\",\r\n    idx_scan AS \"Index Scans\",\r\n    idx_tup_read AS \"Tuples Read\",\r\n    idx_tup_fetch AS \"Tuples Fetched\"\r\nFROM\r\n    pg_stat_all_indexes\r\nWHERE\r\n    schemaname NOT LIKE 'pg_%' AND\r\n    indexrelname IS NOT NULL\r\nORDER BY 3 DESC;"
    }
   ]
  },
  {
   "title": "Database Total Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    pg_size_pretty(SUM(pg_total_relation_size(relid))) As \"Size\"\nFROM \n    pg_catalog.pg_statio_user_tables;"
    }
   ]
  },
  {
   "title": "About Teslamate Custom Dashboards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 14, "x": 10, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT '2024.04.17' AS \"Current Version\""
    }
   ]
  }
 ]
}