image:
  repository: ghcr.io/elfhosted/nzbget
  pullPolicy: IfNotPresent
  tag: 24.4@sha256:7374ee77d5b84bad609b5319d03cbf9fa4a081efe9b6b25f9969630a859e8775
service:
  main:
    ports:
      main:
        port: 10057
        targetPort: 6789
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
