image:
  pullPolicy: IfNotPresent
  repository: docker.io/cloudreve/cloudreve
  tag: 4.1.3@sha256:911fd40bd7c3fc0c4c5543e273863585641b3bb69b8798c9d06f468cbd9f5bf9
persistence:
  avatarpath:
    enabled: true
    mountPath: /cloudreve/avatar
  config:
    enabled: true
    targetSelector:
      main:
        main:
          mountPath: /cloudreve
        init:
          mountPath: /conf-init
  uploadpath:
    enabled: true
    mountPath: /cloudreve/uploads
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      initContainers:
        init:
          enabled: true
          type: init
          imageSelector: image
          command:
          - "/bin/sh"
          - "-c"
          - |
            set -x
            ls -lasth /cloudreve
            cp -a /cloudreve/cloudreve /conf-init/cloudreve
            ls -lasht /conf-init
      containers:
        main: {}
service:
  main:
    ports:
      main:
        port: 5212
        targetPort: 5212
portal:
  open:
    enabled: true
