image:
  repository: ghcr.io/linuxserver/firefox
  pullPolicy: IfNotPresent
  tag: 133.0.3@sha256:95ed2b14929eee46dab9109602063cd85859d4bcab7167319cf12b5ec7a0034d
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        protocol: http
        port: 10131
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
            readiness:
              type: http
            startup:
              type: http
          env:
            FM_HOME: "/config"
            CUSTOM_PORT: "{{ .Values.service.main.ports.main.port }}"
            TITLE: "TrueChartVNC Client"
persistence:
  config:
    enabled: true
    mountPath: /config
  varrun:
    enabled: false
portal:
  open:
    enabled: true
