image:
  repository: docker.io/advplyr/audiobookshelf
  tag: 2.16.1@sha256:5825644df5bb91b1da092edc2b49473e74ae8e2f7f35332fb6489a08c9694ccc
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10223
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/ping"
            readiness:
              path: "/ping"
            startup:
              path: "/ping"
          env:
            AUDIOBOOKSHELF_UID: "{{ .Values.securityContext.container.PUID }}"
            AUDIOBOOKSHELF_GID: "{{ .Values.securityContext.pod.fsGroup }}"
            PORT: "{{ .Values.service.main.ports.main.port }}"
            TOKEN_SECRET:
              secretKeyRef:
                name: secrets
                key: TOKEN_SECRET
persistence:
  config:
    enabled: true
    mountPath: /config
  audiobooks:
    enabled: true
    mountPath: /audiobooks
  metadata:
    enabled: true
    mountPath: /metadata
portal:
  open:
    enabled: true
