image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/recyclarr/recyclarr
  tag: 7.3.0@sha256:2aaa0205a93171b93a159e4665004ccee1a5aacd60359fb8d7683db0ae7e774b
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      initContainers:
        initconfig:
          type: install
          enabled: true
          imageSelector: "image"
          command:
            - recyclarr
            - config
            - create
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            CRON_SCHEDULE: "@daily"
persistence:
  config:
    enabled: true
    mountPath: /config
    targetSelectAll: true
portal:
  open:
    enabled: false
